{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "1.0" %}

package:
  name: ncrc
  version: {{ version }}

source:
  path: ../../ncrc-client

build:
  noarch: python
  number: {{ build }}  # [linux,osx]
  string: {{ strbuild }}
  skip: true # [win]

requirements:
  host:
    - python
  run:
    - python
    - requests
    - conda

test:
  imports:
    - ncrc
  commands:
    - test -f $PREFIX/bin/ncrc

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'Install Conda packages behind a secured location'

extra:
  recipe-maintainers:
    - milljm
