{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set name = "ncrc" %}
{% set version = "1.2" %}
{% set sha256 = "48a1e4011ef624481644560546c8ccdb8d210b44386b3a8824ced6404dece652" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    url: https://hpcgitlab.hpc.inl.gov/idaholab/{{ name }}-client/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: {{ build }}
  string: {{ strbuild }}
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --upgrade-strategy only-if-needed --use-feature=in-tree-build
  entry_points:
    - ncrc = ncrc.__main__:main

requirements:
  host:
    - python >=3.6
    - requests
    - conda
    - pip
  run:
    - python >=3.6
    - requests
    - conda

test:
  imports:
    - rsasecure_login
  commands:
    - rsasecure_login --help

about:
  home: https://hpcgitlab.hpc.inl.gov/idaholab/ncrc-client
  license: BSD-3-Clause OR MIT
  license_file: LICENSE.txt
  summary: Install Conda packages protected by an RSASecurID location
  doc_url: https://hpcgitlab.hpc.inl.gov/idaholab/ncrc-client
  dev_url: https://hpcgitlab.hpc.inl.gov/idaholab/ncrc-client

extra:
  recipe-maintainers:
    - milljm
